Fixed order confirmation not recognized
symt/BazaarNotifier pull request #20
Opened 2020-10-20 23:52 UTC by luguco

Sometimes orders don't get recognized during confimation because the TickEvent is triggered  although the chest gui is not fully loaded yet.
With this fix the lastScreenDisplayName is only set if the gui is fully loaded and itemslot 13 is not null. By that a new order will only be initiated when the gui is fully loaded an all data can be gathered.

2020-10-29 18:00 UTC, symt commented
Oh my, sorry for taking so long to see this.

Is there any need for the three imports added?

```
import org.lwjgl.Sys;
import scala.Console;
import scala.collection.immutable.Stream;
```

2020-10-29 18:04 UTC, symt requested changes
See the comment above

2020-11-20 20:46 UTC, luguco commented
Hi, 
sorry for the long delay. There is no need for those import anymore.

2020-12-09 21:23 UTC, symt commented
> 
> 
> Hi,
> sorry for the long delay. There is no need for those import anymore.

I'll manually delete them. Thanks for doing this.

2020-12-09 21:23 UTC, symt approved these changes

2020-12-09 21:26 UTC, merged